spring.application.name=movie-library

spring.datasource.url=jdbc:postgresql://localhost:5432/movie_library
spring.datasource.username=movie_user
spring.datasource.password=movie_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
